import os
from supabase import create_client, Client
from dotenv import load_dotenv

load_dotenv()

SUBAPASE_URL = os.getenv("NEXT_PUBLIC_SUPABASE_URL")
# Use Service Role Key if available, else Anon Key (but Anon might fail for DDL)
SUPABASE_KEY = os.getenv("SUPABASE_SERVICE_ROLE_KEY") or os.getenv("NEXT_PUBLIC_SUPABASE_ANON_KEY")

def init():
    print(f"Connecting to Supabase at {SUBAPASE_URL}...")
    supabase: Client = create_client(SUBAPASE_URL, SUPABASE_KEY)
    
    # Supabase doesn't support easy 'CREATE TABLE' via Python client without SQL execution permission.
    # We will try a dummy insert to see if it works.
    try:
        print("Checking if 'market_data' table exists...")
        supabase.table("market_data").select("count", count="exact").limit(1).execute()
        print("Success: 'market_data' table exists.")
    except Exception as e:
        print(f"Warning/Error checking table: {e}")
        print("\nIMPORTANT: If the table doesn't exist, please run this SQL in your Supabase Dashboard SQL Editor:")
        print("""
CREATE TABLE IF NOT EXISTS market_data (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  time TEXT,
  vix FLOAT8,
  esf FLOAT8,
  date TEXT,
  "volTide" FLOAT8,
  "coneUp" FLOAT8,
  "coneDown" FLOAT8
);

-- Enable RLS and add a policy to allow public reads
ALTER TABLE market_data ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read access" ON market_data FOR SELECT USING (true);
CREATE POLICY "Allow anon insert" ON market_data FOR INSERT WITH CHECK (true);
        """)

if __name__ == "__main__":
    init()
